name: inventario_app
description: A new Flutter project.
publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- SUPABASE ---
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1

  # --- HERRAMIENTAS DE HARDWARE ---
  image_picker: ^1.1.0
  mobile_scanner: ^6.0.4
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  # --- ICONOS ---
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
